# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [dev, master, feat/**, ci/test, test/**, v7.0]
  pull_request:
    branches: [dev, master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ubuntu-latest
    name: "Lint"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Enable corepack
        run: corepack enable

      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Lint
        run: pnpm lint

  deploy-doc:
    if: ${{ contains(github.actor, 'zhangyuang') && github.ref_name == 'dev' && contains(github.event.head_commit.message, '.md')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 24
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: zhangyuang/v8-profiler-rs
          path: v8-profiler-rs
          ref: public
      - run: |
          cp ./v8-profiler-rs/README.md ./docs/web/markdown/en/features/memory.md
          cp ./v8-profiler-rs/README.md ./docs/web/markdown/zh/features/memory.md
      - run: cd docs && yarn && npm run deploy
        env:
          SERVERLESS_DEPLOY_AK: ${{ secrets.SERVERLESS_DEPLOY_AK }}
          SERVERLESS_DEPLOY_ENDPOINT: ${{ secrets.SERVERLESS_DEPLOY_ENDPOINT }}
          SERVERLESS_DEPLOY_ID: ${{ secrets.SERVERLESS_DEPLOY_ID }}
          SERVERLESS_DEPLOY_SECRET: ${{ secrets.SERVERLESS_DEPLOY_SECRET }}
          SERVERLESS_DEPLOY_TIMEOUT: ${{ secrets.SERVERLESS_DEPLOY_TIMEOUT }}

  e2e-chrome-midway-react:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on

      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:midway:react &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium

  e2e-chrome-nestjs-react-prod:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on

      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:react:prod &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium

  e2e-chrome-nestjs-react18-prod:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on

      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:react18:prod &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium

  e2e-chrome-nestjs-react-prod-vite:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:react:prod:vite &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium
  e2e-chrome-nestjs-react18-prod-vite:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:react18:prod:vite &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium
  e2e-chrome-nestjs-vue3-prod-vite:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:vue3:prod:vite &
          npx wait-on http://localhost:3000
          pnpm e2e tests/common-ssr.spec.ts tests/vue-ssr.spec.ts --project=chromium
  e2e-chrome-nestjs-vue-prod:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:vue:prod &
          npx wait-on http://localhost:3000
          pnpm e2e tests/common-ssr.spec.ts tests/vue-ssr.spec.ts --project=chromium
  e2e-chrome-nestjs-vue3-prod:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:vue3:prod &
          npx wait-on http://localhost:3000
          pnpm e2e tests/common-ssr.spec.ts tests/vue-ssr.spec.ts --project=chromium

  e2e-chrome-midway-react-vite:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:midway:react:vite &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium
  e2e-chrome-midway-vue3-vite:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:midway:vue3:vite &
          npx wait-on http://localhost:3000
          pnpm e2e tests/common-ssr.spec.ts --project=chromium

  e2e-chrome-nestjs-react18-vite:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:react18:vite &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium

  e2e-chrome-nestjs-react-rspack:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:react:rspack &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium

  e2e-chrome-nestjs-react18-rspack:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:react18:rspack &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium

  e2e-chrome-nestjs-react-prod-rspack:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:react:prod:rspack &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium

  e2e-chrome-nestjs-vue3-pinia:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:vue3:pinia &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium

  e2e-chrome-midway-vue3:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:midway:vue3 &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium
  e2e-chrome-nestjs-vue:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:vue &
          npx wait-on http://localhost:3000
          pnpm e2e tests/common-ssr.spec.ts tests/vue-ssr.spec.ts --project=chromium

  e2e-chrome-nestjs-react18:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:react18 &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium
  e2e-chrome-nestjs-vue3:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:vue3 &
          npx wait-on http://localhost:3000
          pnpm e2e tests/noswiper.spec.ts --project=chromium
        env:
          ssrConfig: '{"whiteList":["ssr-common-utils"]}'

  e2e-chrome-nestjs-vue3-rspack:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:vue3:rspack &
          npx wait-on http://localhost:3000
          pnpm e2e tests/common-ssr.spec.ts tests/vue-ssr.spec.ts --project=chromium

  e2e-chrome-nestjs-vue3-prod-rspack:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:vue3:prod:rspack &
          npx wait-on http://localhost:3000
          pnpm e2e tests/common-ssr.spec.ts tests/vue-ssr.spec.ts --project=chromium

  e2e-chrome-nestjs-vue-rspack:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:vue:rspack &
          npx wait-on http://localhost:3000
          pnpm e2e tests/common-ssr.spec.ts tests/vue-ssr.spec.ts --project=chromium

  e2e-chrome-nestjs-vue-prod-rspack:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force && pnpm add -g wait-on
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: Start server and run Playwright tests
        run: |
          pnpm example:nestjs:vue:prod:rspack &
          npx wait-on http://localhost:3000
          pnpm e2e tests/common-ssr.spec.ts tests/vue-ssr.spec.ts --project=chromium
  publish:
    name: Publish
    if: "startsWith(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    needs:
      - lint
      - e2e-chrome-midway-react
      - e2e-chrome-midway-react-vite
      - e2e-chrome-midway-vue3
      - e2e-chrome-midway-vue3-vite
      - e2e-chrome-nestjs-react-prod
      - e2e-chrome-nestjs-react-prod-vite
      - e2e-chrome-nestjs-vue-prod
      - e2e-chrome-nestjs-vue3-prod
      - e2e-chrome-nestjs-vue3-prod-vite
      - e2e-chrome-nestjs-vue
      - e2e-chrome-nestjs-vue3
      - e2e-chrome-nestjs-react18
      - e2e-chrome-nestjs-react18-prod
      - e2e-chrome-nestjs-react18-prod-vite
      - e2e-chrome-nestjs-vue3-pinia
      - e2e-chrome-nestjs-react18-vite
      - e2e-chrome-nestjs-react-rspack
      - e2e-chrome-nestjs-react18-rspack
      - e2e-chrome-nestjs-react-prod-rspack
      - e2e-chrome-nestjs-vue3-rspack
      - e2e-chrome-nestjs-vue3-prod-rspack
      - e2e-chrome-nestjs-vue-rspack
      - e2e-chrome-nestjs-vue-prod-rspack
    strategy:
      matrix:
        node: ["20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.job }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Enable corepack
        run: corepack enable
      - name: Setup pnpm
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          rm -rf node_modules

          pnpm install --no-frozen-lockfile --force
      - name: Build packages
        run: |
          pnpm build

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium

      - name: List packages
        run: ls -R packages
        shell: bash
      - name: pnpm publish
        run: |
          find ./packages/ -type d -maxdepth 1 -exec cp LICENSE {} \;
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          pnpm run ci-publish -- ${{ github.event.head_commit.message }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
